name: CI Front End

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd ./starter/backend
          pipenv install

      - name: Run tests
        run: |
          cd ./starter/backend
          pipenv run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          pip install flake8
          cd ./starter/backend
          pipenv install

      - name: Run tests
        run: |
          cd ./starter/backend
          pipenv run lint
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd ./starter/backend
          pipenv install

      - name: Build Docker image
        run: |
          cd ./starter/frontend
          docker build --tag mp-backend:${{ github.sha }} .
