name: CI Front End

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd ./starter/backend
          pipenv install

      - name: Run tests
        run: |
          cd ./starter/backend
          pipenv run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd ./starter/backend
          pipenv install

      - name: Run tests
        run: |
          cd ./starter/backend
          pipenv run lint
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd ./starter/backend
          pipenv install

      - name: Build Docker image
        run: |
          cd ./starter/frontend
          docker build --tag mp-backend:${{ github.sha }} .

#  deploy:
#    runs-on: ubuntu-latest
#    env:
#      AWS_REGION: your-region  # Set your AWS region
#      AWS_ACCOUNT_ID: your-account-id  # Set your AWS account ID
#      AWS_ECR_NAME: my-frontend-app  # Set your ECR repository name
#    needs: build  # This job will run only if the build job succeeds
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Log in to Amazon ECR
#        uses: aws-actions/amazon-ecr-login@v1
#
#      - name: Push Docker image to ECR
#        run: |
#          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
#          docker tag project-4-frontend-app:${{ github.sha }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.your-region.amazonaws.com/${{ env.AWS_ECR_NAME }}:${{ github.sha }}
#          docker push your-account-id.dkr.ecr.your-region.amazonaws.com/my-frontend-app:${{ github.sha }}
#
#      - name: Deploy to Kubernetes
#        run: |
#          kubectl apply -f k8s/movie-picture-deployment.yaml
